server.port=8084

telegram.bot.token=8653404445:AAG3Xl4iGZSSx_7tKbXEqjLBX9-H7twZc5Y

spring.datasource.url=jdbc:postgresql://localhost:5432/astana
spring.datasource.username=neo
spring.datasource.password=dyalpsoge

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.change-log=classpath:liquibase/scripts/script.sql

spring.task.scheduling.pool.size=2
app.upload-dir=upload/reports
logging.level.com.example.nurseryAstana.service=DEBUG
