server.port=8080

telegram.bot.token=secret

spring.datasource.url=jdbc:postgresql://localhost:5432/astana
spring.datasource.username=secret
spring.datasource.password=secret

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.change-log=classpath:liquibase/scripts/script.sql

spring.task.scheduling.pool.size=2
app.upload-dir=uploads/reports
logging.level.com.example.nurseryAstana.service=DEBUG